version: '3.9'
services:
  web:
    build:
      context: .
      args:
        DEV: 'true'
    command: 'npm run server:dev'
    ports:
      - '8080:8080'
      - '9229:9229'
    env_file: .env.local
    volumes:
      - './src:/app/src'
